### ISSUE TITLE
Support newer versions of php codesniffer

### ISSUE THREAD

**Issue by mrrsm** [codacy/codacy-codesniffer#17]
The current build pulls in "squizlabs/php_codesniffer=2.9.1" which was released on May 21, 2017
Ideally we should be able to use the ^3.0 version (that will pull in the latest 3.x which as of right now is 3.3.1).  The downside is if someone hasn't updated their sniffs to be up to date with the latest CodeSniffer package they will no longer work.  However it has been over a year and they provide a [guide to upgrade](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Version-3.0-Upgrade-Guide)

It does look like the standards which you pull in as defaults all support php codesniffer 3.0+ though you would probably have to update to a later branch/tag on most of them.
The only one I see with a potential issue is [Magento](https://github.com/magento/marketplace-eqp/issues/75#issuecomment-378180753) though you can pull master down and it supports version 3+.

**Comment by rtfpessoa** [comment]
@mrrsm sorry for the delay. We are analysing this to and will let you know when we have updates.
PRs are always welcome.

**Comment by Laracodacy** [comment]
Hi,

We currently support PHP Code Sniffer 3.3.2. We have a different issue to continue to update https://github.com/codacy/codacy-meta/issues/24

Thanks
