### ISSUE TITLE
custom phpcs.xml : SlevomatCodingStandard.Files.TypeNameMatchesFileName properties ignored?

### ISSUE THREAD

**Issue by bkdotcom** [codacy/codacy-codesniffer#45]
Now that my custom phpcs.xml  is working and phpcs isn't complaining about unable to find sniffs (thanks for the phpcs/slevomat update).  I'm seeing an issue with one of the included sniffs

```
    <rule ref="SlevomatCodingStandard.Files.TypeNameMatchesFileName">
        <properties>
            <property name="rootNamespaces" type="array">
                <element key="src" value="RootNamespace"/>
            </property>
        </properties>
        <exclude-patter>src/namespace/Classname.php</exclude-pattern>
    </rule>
```

I'm getting this issue
> Class name RootNamespace\namespace\Classname does not match filepath /src/src/RootNamespace/namespace/Classname.php

it should be trying to match `/src/namespace/Classname.php`.  
It's as if the properties I've defined in phpcs.xml are being overwritten?

or (more likely) : as if my project is extracted to a `/src` directory on the phpcs virtual-machine and the rootNamespaces property I've defined is just being ignored (vs overwritten)

The file specified by exclude-pattern is not throwing an error.  so `<exclude-pattern>` is working

**Comment by franciscodua** [comment]
That's exactly it.

As you can see in the project [README](https://github.com/codacy/codacy-codesniffer#usage), your source directory is mapped to the container's directory `/src`. Which means the result will be `/src/<your code>`.

Unfortunately, it's not possible to define a root path when running this tool, which means we cannot ignore the `/src` part of the absolute path. As you can see in the slevomat's repository there's already an [issue](https://github.com/slevomat/coding-standard/issues/214) related to this problem, but no concrete solution.

As a workaround you can change your configuration file to add `src` as a directory to skip:
```
<rule ref="SlevomatCodingStandard.Files.TypeNameMatchesFileName">
    <properties>
        <property name="rootNamespaces" type="array">
            <element key="src" value="RootNamespace"/>
        </property>
        <property name="skipDirs" type="array" value="src,"/>
    </properties>
    <exclude-pattern>src/namespace/Classname.php</exclude-pattern>
</rule>
```

I hope this solves you problem and we appreciate your feedback.
Feel free to get back to us if you have any other question or concern.

**Comment by bkdotcom** [comment]
I'll give that solution a try.  
Thanks

For now I'm excluding that sniff/check altogether..  Unit tests _should_ expose this issue

**Comment by franciscodua** [comment]
You're welcome. I'll close this issue but you can re-open it or create a new one if you have further questions regarding this problem.
