### ISSUE TITLE
Add custom standard like PHPCompatibility

### ISSUE THREAD

**Issue by Mte90** [codacy/codacy-codesniffer#60]
I am wondering how it is possible to add more sniffer like:

* https://github.com/WordPress/WordPress-Coding-Standards
* https://github.com/PHPCompatibility/PHPCompatibility

Right now locally is enough to install it with composer but on the codacy wiki there is no explanation how to use them.

**Comment by josemiguelmelo** [comment]
Hi @Mte90,

First of all, thanks for the interest in contributing by adding another sniffer 🙂

About the process of adding more sniffers, it consists mainly in 2 parts:
1. Add the dependency to `composer.json` inside this repository
2. Add a documentation parser for the sniffer you're adding and generate that documentation

I added a more detailed information on how to do it to our [README.md](https://github.com/codacy/codacy-codesniffer#add-new-codesniffer-plugin).

**Comment by Mte90** [comment]
As I can see phpcompatibility is already avalaible is missing just the wordpress one.
I can try with a pull request.

**Comment by Mte90** [comment]
Both of them are already integrated in this repo so this ticket can be closed.

**Comment by josemiguelmelo** [comment]
I'm glad to know that the sniffers you needed are already supported. 
Thanks for the interest and for the contribution 👍
