### ISSUE TITLE
Parameters not showing in the UI

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-codesniffer#85]
Parameters are defined in the `patterns.json`, but not in the `description.json` file.
This makes the UI skip them.

codacy-plugins-test json tests are skipped in CI:
https://github.com/codacy/codacy-codesniffer/blob/5ce7ee089b825543f7e3debf71ab4c09a2e1fc9d/.circleci/config.yml#L38

### Acceptance criteria
No parameters are deleted and codacy-plugins-test json test is enabled and green in CI

**Comment by josemiguelmelo** [comment]
This problem should be already fixed in production.
